# Generated by Django 4.2.1 on 2024-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='message',
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(to='chat.message'),
        ),
    ]
